spring.application.name=PetStoreApplication

server.port=8080

server.error.include-binding-errors=always
server.error.include-message=always
server.error.include-stacktrace=never

spring.datasource.url=jdbc:postgresql://localhost:5432/pet_store_db
spring.datasource.username=techpront
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

logging.file.name=log/pet_app.log
logging.pattern.file= "%d %-5level - [%thread] %logger:%msg%n"
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.com.avsarzirh=INFO

# Uygulamamiz ile ilgili propertyleri istedigimiz gibi tanimlayabiliriz.
# Ornek
# abuzer.herhangi.bir.property=value
app.jwtSecret=udG82zRmwp54oW4Mq2gFRAsQiXGS86PD
app.jwtExpiartionMs=86400000